name: Sync with upstream and create pull request

on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight UTC
  workflow_dispatch:       # allow manual trigger

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync test-upstream with upstream/main

    steps:
      - name: Checkout upstream-sync branch
        uses: actions/checkout@v4
        with:
          ref: upstream-sync
          fetch-depth: 0  # Make sure full history is available

      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          target_sync_branch: upstream-sync
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_branch: main
          upstream_sync_repo: Basit-raza01/test-upstream  # Changed upstream repository

      - name: Show sync result
        run: echo '${{ steps.sync.outputs.has_new_commits }}'

  create_pull_request:
    runs-on: ubuntu-latest
    name: Create a pull request into main

    needs: sync_with_upstream

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Fetch synced branch
        run: git fetch origin upstream-sync:upstream-sync

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: upstream-sync      
          base: main
          title: 'Sync with upstream'
          body: 'Automated pull request to merge updates from upstream.'
          commit-message: 'chore: merge upstream updates into main'
